model: 
    m_type : "language"
    checkpoint_path : "./models/language"

running_params: 
    batch_size : 32 
    shuffle : true
    n_workers : 4 
    lr : 0.1
    n_epochs : 20 
    patience : 5 
    device: "cuda:0"

log_params: 
    hug_password : "Zt()567kjhgLT76vfhle&%"
    HUGGING_FACE_HUB_TOKEN : "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"

data: 
    path : './data/coco_data'
    n_classes : 80
    experiment_name : "llama_3B_coco_multilabel"
